Initial commit with working Cirrus configuration.

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -1,19 +1,23 @@
 #!/usr/bin/bash -l
 <%
 
+# The user's EPCCFS directory needs to be set here independently of the change to
+# HOME in before.sh.erb, as this is Ruby now -- it happens before any bash.
+epccfs_base = Pathname.new(ENV['HOME'].sub(%r{\A/home/}, '/epccfs/'))
+
 # Set our working directory.
 working_dir = Pathname.new(context.working_dir)
 
-# Ensure that code-server always starts up in either a user defined directory or the home directory.
+# Ensure that code-server always starts up in either a user defined directory or the user's EPCCFS directory.
 if ! working_dir.exist?
-    working_dir = Pathname.new(ENV['HOME'])
+    working_dir = epccfs_base
 elsif working_dir.file?
     working_dir = working_dir.parent
 end
 %>
 
 CODE_SERVER_DATAROOT="$HOME/.local/share/code-server"
-mkdir -p "$CODE_SERVER_DATAROOT/extensions"
+mkdir -p "$CODE_SERVER_DATAROOT/extensions" "$CODE_SERVER_DATAROOT/Machine" "$CODE_SERVER_DATAROOT/User"
 
 # Expose the password to the server.
 export PASSWORD="$password"
@@ -21,28 +25,17 @@ export PASSWORD="$password"
 # Print compute node.
 echo "$(date): Running on compute node $(hostname):$port"
 
-module load project/ondemand <%= context.auto_modules_app_code_server %>
+# If in the future we have a code-server module, load it here.
+# For now, set its location here to later be called directly below.
+CODE_SERVER_BASE=/epccfs/z19/z19/wlucas/opt/code-server
+CODE_SERVER_EXEC=/epccfs/z19/z19/wlucas/opt/code-server/code-server-4.141.0-linux-amd64/bin/code-server
+#SITE_DEFAULTS=${CODE_SERVER_BASE}/site
 
-CPP_FILE="<%= working_dir.to_s %>/.vscode/c_cpp_properties.json"
-
-if [[ -f "$CPP_FILE" ]]; then
-    CPP_DIR="${TMPDIR:=/tmp/$USER}/cpp-vscode"
-    mkdir -p "$CPP_DIR"
-    chmod 700 "$CPP_DIR"
-
-    # if the file is empty, let's initialize it
-    [ -s "$CPP_FILE" ] || echo '{"configurations": [{ "name": "Linux", "browse": { "databaseFilename": null }}], "version": 4}' > "$CPP_FILE"
-
-    jq --arg dbfile "$CPP_DIR/cpp-vscode.db" \
-      '.configurations[0].browse.databaseFilename = $dbfile' \
-      "$CPP_FILE" > "$CPP_FILE".new
-
-    mv "$CPP_FILE".new "$CPP_FILE"
-  fi
-
-# Copy machine settings file
-mkdir -p "$CODE_SERVER_DATAROOT/Machine"
-cp "$CODE_SERVER_MACHINE_SETTINGS" "$CODE_SERVER_DATAROOT/Machine/settings.json"
+# Copy default site settings into place. Do this every time, in case CSE make changes we want to
+# propagate to user runs. That file's helpful, as it stops code-server doing things we don't want
+# like tracking large git object trees, so exit if it can't be copied over for whatever reason.
+cp machine-settings.json "$CODE_SERVER_DATAROOT/Machine/settings.json" \
+  || { echo "ERROR: site settings not found at $SITE_DEFAULTS" >&2; exit 1; }
 
 #
 # Start Code Server.
@@ -50,10 +43,12 @@ cp "$CODE_SERVER_MACHINE_SETTINGS" "$CODE_SERVER_DATAROOT/Machine/settings.json"
 echo "$(date): Started code-server"
 echo ""
 
-code-server \
+# maybe get rid of --log debug in production?
+"${CODE_SERVER_EXEC}" \
     --auth="password" \
     --bind-addr="0.0.0.0:${port}" \
     --disable-telemetry \
+    --disable-update-check \
     --ignore-last-opened \
     --user-data-dir="$CODE_SERVER_DATAROOT" \
     --log debug \
